# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:/python/typer/ui_en_sentencewindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_en_sentencewindow(object):
    def setupUi(self, en_sentencewindow):
        en_sentencewindow.setObjectName("en_sentencewindow")
        en_sentencewindow.resize(999, 554)
        en_sentencewindow.setMinimumSize(QtCore.QSize(999, 554))
        en_sentencewindow.setMaximumSize(QtCore.QSize(999, 554))
        font = QtGui.QFont()
        font.setFamily("黑体")
        en_sentencewindow.setFont(font)
        en_sentencewindow.setStyleSheet("color=rgb(255, 0, 0)")
        self.sentence1_input = QtWidgets.QLineEdit(en_sentencewindow)
        self.sentence1_input.setGeometry(QtCore.QRect(80, 100, 811, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sentence1_input.setFont(font)
        self.sentence1_input.setText("")
        self.sentence1_input.setMaxLength(50)
        self.sentence1_input.setObjectName("sentence1_input")
        self.warning1_set = QtWidgets.QLabel(en_sentencewindow)
        self.warning1_set.setGeometry(QtCore.QRect(10, 110, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.warning1_set.setFont(font)
        self.warning1_set.setStyleSheet("color:red")
        self.warning1_set.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.warning1_set.setObjectName("warning1_set")
        self.sentence1_set = QtWidgets.QLabel(en_sentencewindow)
        self.sentence1_set.setGeometry(QtCore.QRect(80, 30, 841, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.sentence1_set.setFont(font)
        self.sentence1_set.setObjectName("sentence1_set")
        self.label_3 = QtWidgets.QLabel(en_sentencewindow)
        self.label_3.setGeometry(QtCore.QRect(40, 510, 41, 21))
        self.label_3.setObjectName("label_3")
        self.time_used_set = QtWidgets.QLabel(en_sentencewindow)
        self.time_used_set.setGeometry(QtCore.QRect(100, 510, 101, 21))
        self.time_used_set.setObjectName("time_used_set")
        self.label_5 = QtWidgets.QLabel(en_sentencewindow)
        self.label_5.setGeometry(QtCore.QRect(240, 510, 41, 21))
        self.label_5.setObjectName("label_5")
        self.type_speed_set = QtWidgets.QLabel(en_sentencewindow)
        self.type_speed_set.setGeometry(QtCore.QRect(290, 510, 161, 21))
        self.type_speed_set.setObjectName("type_speed_set")
        self.sentence2_input = QtWidgets.QLineEdit(en_sentencewindow)
        self.sentence2_input.setGeometry(QtCore.QRect(80, 260, 811, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sentence2_input.setFont(font)
        self.sentence2_input.setText("")
        self.sentence2_input.setMaxLength(50)
        self.sentence2_input.setObjectName("sentence2_input")
        self.sentence2_set = QtWidgets.QLabel(en_sentencewindow)
        self.sentence2_set.setGeometry(QtCore.QRect(80, 190, 861, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sentence2_set.setFont(font)
        self.sentence2_set.setObjectName("sentence2_set")
        self.sentence3_input = QtWidgets.QLineEdit(en_sentencewindow)
        self.sentence3_input.setGeometry(QtCore.QRect(80, 420, 811, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sentence3_input.setFont(font)
        self.sentence3_input.setText("")
        self.sentence3_input.setMaxLength(50)
        self.sentence3_input.setObjectName("sentence3_input")
        self.sentence3_set = QtWidgets.QLabel(en_sentencewindow)
        self.sentence3_set.setGeometry(QtCore.QRect(80, 350, 861, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sentence3_set.setFont(font)
        self.sentence3_set.setObjectName("sentence3_set")
        self.warning2_set = QtWidgets.QLabel(en_sentencewindow)
        self.warning2_set.setGeometry(QtCore.QRect(10, 270, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.warning2_set.setFont(font)
        self.warning2_set.setStyleSheet("color:red")
        self.warning2_set.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.warning2_set.setObjectName("warning2_set")
        self.warning3_set = QtWidgets.QLabel(en_sentencewindow)
        self.warning3_set.setGeometry(QtCore.QRect(10, 430, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.warning3_set.setFont(font)
        self.warning3_set.setStyleSheet("color:red")
        self.warning3_set.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.warning3_set.setObjectName("warning3_set")

        self.retranslateUi(en_sentencewindow)
        QtCore.QMetaObject.connectSlotsByName(en_sentencewindow)

    def retranslateUi(self, en_sentencewindow):
        _translate = QtCore.QCoreApplication.translate
        en_sentencewindow.setWindowTitle(_translate("en_sentencewindow", "Form"))
        self.sentence1_input.setPlaceholderText(_translate("en_sentencewindow", "start here..."))
        self.warning1_set.setText(_translate("en_sentencewindow", "*输错!"))
        self.sentence1_set.setText(_translate("en_sentencewindow", "sentence1"))
        self.label_3.setText(_translate("en_sentencewindow", "用时:"))
        self.time_used_set.setText(_translate("en_sentencewindow", "0时0分0秒"))
        self.label_5.setText(_translate("en_sentencewindow", "速度:"))
        self.type_speed_set.setText(_translate("en_sentencewindow", "0字/秒"))
        self.sentence2_input.setPlaceholderText(_translate("en_sentencewindow", "start here..."))
        self.sentence2_set.setText(_translate("en_sentencewindow", "sentence2"))
        self.sentence3_input.setPlaceholderText(_translate("en_sentencewindow", "start here..."))
        self.sentence3_set.setText(_translate("en_sentencewindow", "sentence3"))
        self.warning2_set.setText(_translate("en_sentencewindow", "*输错!"))
        self.warning3_set.setText(_translate("en_sentencewindow", "*输错!"))

