# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:/python/typer/ui_keyboardwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_keyboardwindow(object):
    def setupUi(self, keyboardwindow):
        keyboardwindow.setObjectName("keyboardwindow")
        keyboardwindow.resize(999, 554)
        keyboardwindow.setMinimumSize(QtCore.QSize(999, 554))
        keyboardwindow.setMaximumSize(QtCore.QSize(999, 554))
        font = QtGui.QFont()
        font.setFamily("黑体")
        keyboardwindow.setFont(font)
        keyboardwindow.setStyleSheet("color=rgb(255, 0, 0)")
        self.label = QtWidgets.QLabel(keyboardwindow)
        self.label.setGeometry(QtCore.QRect(10, 60, 971, 451))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("source/pics/pic_keyboard.png"))
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(keyboardwindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(46, 80, 931, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setContentsMargins(34, 60, -1, 0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.radio_q = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_q.setText("")
        self.radio_q.setIconSize(QtCore.QSize(20, 20))
        self.radio_q.setObjectName("radio_q")
        self.gridLayout_23.addWidget(self.radio_q, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setContentsMargins(59, -1, -1, -1)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.radio_f = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_f.setText("")
        self.radio_f.setIconSize(QtCore.QSize(20, 20))
        self.radio_f.setObjectName("radio_f")
        self.gridLayout_36.addWidget(self.radio_f, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_36, 1, 3, 1, 1)
        self.gridLayout_38 = QtWidgets.QGridLayout()
        self.gridLayout_38.setContentsMargins(58, -1, -1, -1)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.radio_h = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_h.setText("")
        self.radio_h.setIconSize(QtCore.QSize(20, 20))
        self.radio_h.setObjectName("radio_h")
        self.gridLayout_38.addWidget(self.radio_h, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_38, 1, 5, 1, 1)
        self.gridLayout_37 = QtWidgets.QGridLayout()
        self.gridLayout_37.setContentsMargins(60, -1, -1, -1)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.radio_g = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_g.setText("")
        self.radio_g.setIconSize(QtCore.QSize(20, 20))
        self.radio_g.setObjectName("radio_g")
        self.gridLayout_37.addWidget(self.radio_g, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_37, 1, 4, 1, 1)
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setContentsMargins(21, 60, -1, -1)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.radio_w = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_w.setText("")
        self.radio_w.setIconSize(QtCore.QSize(20, 20))
        self.radio_w.setObjectName("radio_w")
        self.gridLayout_25.addWidget(self.radio_w, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_25, 0, 1, 1, 1)
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setContentsMargins(20, 60, -1, -1)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.radio_e = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_e.setText("")
        self.radio_e.setIconSize(QtCore.QSize(20, 20))
        self.radio_e.setObjectName("radio_e")
        self.gridLayout_26.addWidget(self.radio_e, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_26, 0, 2, 1, 1)
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setContentsMargins(11, 60, -1, -1)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.radio_u = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_u.setText("")
        self.radio_u.setIconSize(QtCore.QSize(20, 20))
        self.radio_u.setObjectName("radio_u")
        self.gridLayout_30.addWidget(self.radio_u, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_30, 0, 6, 1, 1)
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setContentsMargins(12, 60, -1, -1)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.radio_y = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_y.setText("")
        self.radio_y.setIconSize(QtCore.QSize(20, 20))
        self.radio_y.setObjectName("radio_y")
        self.gridLayout_29.addWidget(self.radio_y, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_29, 0, 5, 1, 1)
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setContentsMargins(15, 60, -1, -1)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.radio_t = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_t.setText("")
        self.radio_t.setIconSize(QtCore.QSize(20, 20))
        self.radio_t.setObjectName("radio_t")
        self.gridLayout_24.addWidget(self.radio_t, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_24, 0, 4, 1, 1)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setContentsMargins(8, 60, -1, -1)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.radio_i = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_i.setText("")
        self.radio_i.setIconSize(QtCore.QSize(20, 20))
        self.radio_i.setObjectName("radio_i")
        self.gridLayout_31.addWidget(self.radio_i, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_31, 0, 7, 1, 1)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setContentsMargins(0, 60, 0, -1)
        self.gridLayout_33.setHorizontalSpacing(7)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.radio_p = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_p.setText("")
        self.radio_p.setIconSize(QtCore.QSize(20, 20))
        self.radio_p.setObjectName("radio_p")
        self.gridLayout_33.addWidget(self.radio_p, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_33, 0, 9, 1, 1)
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setContentsMargins(65, -1, -1, -1)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.radio_d = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_d.setText("")
        self.radio_d.setIconSize(QtCore.QSize(20, 20))
        self.radio_d.setObjectName("radio_d")
        self.gridLayout_35.addWidget(self.radio_d, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_35, 1, 2, 1, 1)
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setContentsMargins(5, 60, 0, -1)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.radio_o = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_o.setText("")
        self.radio_o.setIconSize(QtCore.QSize(20, 20))
        self.radio_o.setObjectName("radio_o")
        self.gridLayout_32.addWidget(self.radio_o, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_32, 0, 8, 1, 1)
        self.gridLayout_43 = QtWidgets.QGridLayout()
        self.gridLayout_43.setContentsMargins(63, -1, -1, -1)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.radio_c = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_c.setText("")
        self.radio_c.setIconSize(QtCore.QSize(20, 20))
        self.radio_c.setObjectName("radio_c")
        self.gridLayout_43.addWidget(self.radio_c, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_43, 2, 3, 1, 1)
        self.gridLayout_39 = QtWidgets.QGridLayout()
        self.gridLayout_39.setContentsMargins(58, -1, -1, -1)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.radio_j = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_j.setText("")
        self.radio_j.setIconSize(QtCore.QSize(20, 20))
        self.radio_j.setObjectName("radio_j")
        self.gridLayout_39.addWidget(self.radio_j, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_39, 1, 6, 1, 1)
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setContentsMargins(68, -1, -1, -1)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.radio_s = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_s.setText("")
        self.radio_s.setIconSize(QtCore.QSize(20, 20))
        self.radio_s.setObjectName("radio_s")
        self.gridLayout_34.addWidget(self.radio_s, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_34, 1, 1, 1, 1)
        self.gridLayout_45 = QtWidgets.QGridLayout()
        self.gridLayout_45.setContentsMargins(58, -1, -1, -1)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.radio_b = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_b.setText("")
        self.radio_b.setIconSize(QtCore.QSize(20, 20))
        self.radio_b.setObjectName("radio_b")
        self.gridLayout_45.addWidget(self.radio_b, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_45, 2, 5, 1, 1)
        self.gridLayout_42 = QtWidgets.QGridLayout()
        self.gridLayout_42.setContentsMargins(65, -1, -1, -1)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.radio_x = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_x.setText("")
        self.radio_x.setIconSize(QtCore.QSize(20, 20))
        self.radio_x.setObjectName("radio_x")
        self.gridLayout_42.addWidget(self.radio_x, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_42, 2, 2, 1, 1)
        self.gridLayout_41 = QtWidgets.QGridLayout()
        self.gridLayout_41.setContentsMargins(50, -1, -1, -1)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.radio_l = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_l.setText("")
        self.radio_l.setIconSize(QtCore.QSize(20, 20))
        self.radio_l.setObjectName("radio_l")
        self.gridLayout_41.addWidget(self.radio_l, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_41, 1, 8, 1, 1)
        self.gridLayout_46 = QtWidgets.QGridLayout()
        self.gridLayout_46.setContentsMargins(57, -1, -1, -1)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.radio_n = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_n.setText("")
        self.radio_n.setIconSize(QtCore.QSize(20, 20))
        self.radio_n.setObjectName("radio_n")
        self.gridLayout_46.addWidget(self.radio_n, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_46, 2, 6, 1, 1)
        self.gridLayout_44 = QtWidgets.QGridLayout()
        self.gridLayout_44.setContentsMargins(60, -1, -1, -1)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.radio_v = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_v.setText("")
        self.radio_v.setIconSize(QtCore.QSize(20, 20))
        self.radio_v.setObjectName("radio_v")
        self.gridLayout_44.addWidget(self.radio_v, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_44, 2, 4, 1, 1)
        self.gridLayout_40 = QtWidgets.QGridLayout()
        self.gridLayout_40.setContentsMargins(53, -1, -1, -1)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.radio_k = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_k.setText("")
        self.radio_k.setIconSize(QtCore.QSize(20, 20))
        self.radio_k.setObjectName("radio_k")
        self.gridLayout_40.addWidget(self.radio_k, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_40, 1, 7, 1, 1)
        self.gridLayout_47 = QtWidgets.QGridLayout()
        self.gridLayout_47.setContentsMargins(55, -1, -1, -1)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.radio_m = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_m.setText("")
        self.radio_m.setIconSize(QtCore.QSize(20, 20))
        self.radio_m.setObjectName("radio_m")
        self.gridLayout_47.addWidget(self.radio_m, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_47, 2, 7, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(65, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radio_z = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_z.setText("")
        self.radio_z.setIconSize(QtCore.QSize(20, 20))
        self.radio_z.setObjectName("radio_z")
        self.gridLayout_2.addWidget(self.radio_z, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 1, 1, 1)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setContentsMargins(15, 60, -1, -1)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.radio_r = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_r.setText("")
        self.radio_r.setIconSize(QtCore.QSize(20, 20))
        self.radio_r.setObjectName("radio_r")
        self.gridLayout_27.addWidget(self.radio_r, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_27, 0, 3, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setContentsMargins(80, -1, -1, -1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.radio_a = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_a.setText("")
        self.radio_a.setIconSize(QtCore.QSize(20, 20))
        self.radio_a.setObjectName("radio_a")
        self.gridLayout_10.addWidget(self.radio_a, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.gridLayout_49 = QtWidgets.QGridLayout()
        self.gridLayout_49.setContentsMargins(55, -1, -1, -1)
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.radio_clear = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_clear.setText("")
        self.radio_clear.setIconSize(QtCore.QSize(20, 20))
        self.radio_clear.setChecked(True)
        self.radio_clear.setObjectName("radio_clear")
        self.gridLayout_49.addWidget(self.radio_clear, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_49, 2, 8, 1, 1)
        self.btn_back_menu1 = QtWidgets.QPushButton(keyboardwindow)
        self.btn_back_menu1.setGeometry(QtCore.QRect(880, 17, 93, 28))
        self.btn_back_menu1.setObjectName("btn_back_menu1")

        self.retranslateUi(keyboardwindow)
        QtCore.QMetaObject.connectSlotsByName(keyboardwindow)

    def retranslateUi(self, keyboardwindow):
        _translate = QtCore.QCoreApplication.translate
        keyboardwindow.setWindowTitle(_translate("keyboardwindow", "Form"))
        self.radio_q.setShortcut(_translate("keyboardwindow", "Q"))
        self.radio_f.setShortcut(_translate("keyboardwindow", "F"))
        self.radio_h.setShortcut(_translate("keyboardwindow", "H"))
        self.radio_g.setShortcut(_translate("keyboardwindow", "G"))
        self.radio_w.setShortcut(_translate("keyboardwindow", "W"))
        self.radio_e.setShortcut(_translate("keyboardwindow", "E"))
        self.radio_u.setShortcut(_translate("keyboardwindow", "U"))
        self.radio_y.setShortcut(_translate("keyboardwindow", "Y"))
        self.radio_t.setShortcut(_translate("keyboardwindow", "T"))
        self.radio_i.setShortcut(_translate("keyboardwindow", "I"))
        self.radio_p.setShortcut(_translate("keyboardwindow", "P"))
        self.radio_d.setShortcut(_translate("keyboardwindow", "D"))
        self.radio_o.setShortcut(_translate("keyboardwindow", "O"))
        self.radio_c.setShortcut(_translate("keyboardwindow", "C"))
        self.radio_j.setShortcut(_translate("keyboardwindow", "J"))
        self.radio_s.setShortcut(_translate("keyboardwindow", "S"))
        self.radio_b.setShortcut(_translate("keyboardwindow", "B"))
        self.radio_x.setShortcut(_translate("keyboardwindow", "X"))
        self.radio_l.setShortcut(_translate("keyboardwindow", "L"))
        self.radio_n.setShortcut(_translate("keyboardwindow", "N"))
        self.radio_v.setShortcut(_translate("keyboardwindow", "V"))
        self.radio_k.setShortcut(_translate("keyboardwindow", "K"))
        self.radio_m.setShortcut(_translate("keyboardwindow", "M"))
        self.radio_z.setShortcut(_translate("keyboardwindow", "Z"))
        self.radio_r.setShortcut(_translate("keyboardwindow", "R"))
        self.radio_a.setShortcut(_translate("keyboardwindow", "A"))
        self.btn_back_menu1.setText(_translate("keyboardwindow", "BACK"))

