# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:/python/typer/ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(1000, 680)
        mainwindow.setMinimumSize(QtCore.QSize(1000, 680))
        mainwindow.setMaximumSize(QtCore.QSize(1000, 680))
        mainwindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 911, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.grid_menu2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.grid_menu2.setContentsMargins(25, 0, 0, 0)
        self.grid_menu2.setSpacing(0)
        self.grid_menu2.setObjectName("grid_menu2")
        self.radio_ch_word = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_ch_word.setObjectName("radio_ch_word")
        self.grid_menu2.addWidget(self.radio_ch_word)
        self.radio_ch_sentence = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_ch_sentence.setObjectName("radio_ch_sentence")
        self.grid_menu2.addWidget(self.radio_ch_sentence)
        self.radio_en_word = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_en_word.setObjectName("radio_en_word")
        self.grid_menu2.addWidget(self.radio_en_word)
        self.radio_en_sentence = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_en_sentence.setObjectName("radio_en_sentence")
        self.grid_menu2.addWidget(self.radio_en_sentence)
        self.radio_blank_menu = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_blank_menu.setText("")
        self.radio_blank_menu.setObjectName("radio_blank_menu")
        self.grid_menu2.addWidget(self.radio_blank_menu)
        self.grid_menu2.setStretch(0, 1)
        self.grid_menu2.setStretch(1, 1)
        self.grid_menu2.setStretch(2, 1)
        self.grid_menu2.setStretch(3, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 80, 1001, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_widget = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_widget.setContentsMargins(0, 0, 0, 0)
        self.grid_widget.setObjectName("grid_widget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(340, 260, 351, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.grid_menu1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.grid_menu1.setContentsMargins(0, 0, 0, 0)
        self.grid_menu1.setObjectName("grid_menu1")
        self.radio_key = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/pics/icon_key.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radio_key.setIcon(icon)
        self.radio_key.setIconSize(QtCore.QSize(40, 40))
        self.radio_key.setObjectName("radio_key")
        self.grid_menu1.addWidget(self.radio_key)
        self.radio_type = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("source/pics/icon_type.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radio_type.setIcon(icon1)
        self.radio_type.setIconSize(QtCore.QSize(40, 40))
        self.radio_type.setObjectName("radio_type")
        self.grid_menu1.addWidget(self.radio_type)
        self.radio_blank = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radio_blank.setText("")
        self.radio_blank.setObjectName("radio_blank")
        self.grid_menu1.addWidget(self.radio_blank)
        self.grid_menu1.setStretch(0, 1)
        self.grid_menu1.setStretch(1, 1)
        self.label_welcome = QtWidgets.QLabel(self.centralwidget)
        self.label_welcome.setGeometry(QtCore.QRect(240, 70, 501, 51))
        self.label_welcome.setObjectName("label_welcome")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(882, 98, 93, 28))
        self.btn_back.setObjectName("btn_back")
        mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_4 = QtWidgets.QMenu(self.menu)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menu)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menu)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menu)
        self.menu_7.setObjectName("menu_7")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)
        self.action_offline_rank = QtWidgets.QAction(mainwindow)
        self.action_offline_rank.setObjectName("action_offline_rank")
        self.action_ch_word_low = QtWidgets.QAction(mainwindow)
        self.action_ch_word_low.setCheckable(True)
        self.action_ch_word_low.setChecked(True)
        self.action_ch_word_low.setObjectName("action_ch_word_low")
        self.action_ch_word_mid = QtWidgets.QAction(mainwindow)
        self.action_ch_word_mid.setCheckable(True)
        self.action_ch_word_mid.setObjectName("action_ch_word_mid")
        self.action_ch_word_high = QtWidgets.QAction(mainwindow)
        self.action_ch_word_high.setCheckable(True)
        self.action_ch_word_high.setObjectName("action_ch_word_high")
        self.action_ch_sentence_low = QtWidgets.QAction(mainwindow)
        self.action_ch_sentence_low.setCheckable(True)
        self.action_ch_sentence_low.setChecked(True)
        self.action_ch_sentence_low.setObjectName("action_ch_sentence_low")
        self.action_ch_sentence_mid = QtWidgets.QAction(mainwindow)
        self.action_ch_sentence_mid.setCheckable(True)
        self.action_ch_sentence_mid.setObjectName("action_ch_sentence_mid")
        self.action_ch_sentence_high = QtWidgets.QAction(mainwindow)
        self.action_ch_sentence_high.setCheckable(True)
        self.action_ch_sentence_high.setObjectName("action_ch_sentence_high")
        self.action_en_word_low = QtWidgets.QAction(mainwindow)
        self.action_en_word_low.setCheckable(True)
        self.action_en_word_low.setChecked(True)
        self.action_en_word_low.setObjectName("action_en_word_low")
        self.action_en_word_mid = QtWidgets.QAction(mainwindow)
        self.action_en_word_mid.setCheckable(True)
        self.action_en_word_mid.setObjectName("action_en_word_mid")
        self.action_en_word_high = QtWidgets.QAction(mainwindow)
        self.action_en_word_high.setCheckable(True)
        self.action_en_word_high.setObjectName("action_en_word_high")
        self.action_en_sentence_low = QtWidgets.QAction(mainwindow)
        self.action_en_sentence_low.setCheckable(True)
        self.action_en_sentence_low.setChecked(True)
        self.action_en_sentence_low.setObjectName("action_en_sentence_low")
        self.action_en_sentence_mid = QtWidgets.QAction(mainwindow)
        self.action_en_sentence_mid.setCheckable(True)
        self.action_en_sentence_mid.setObjectName("action_en_sentence_mid")
        self.action_en_sentence_high = QtWidgets.QAction(mainwindow)
        self.action_en_sentence_high.setCheckable(True)
        self.action_en_sentence_high.setObjectName("action_en_sentence_high")
        self.action_about = QtWidgets.QAction(mainwindow)
        self.action_about.setObjectName("action_about")
        self.menu_4.addAction(self.action_ch_word_low)
        self.menu_4.addAction(self.action_ch_word_mid)
        self.menu_4.addAction(self.action_ch_word_high)
        self.menu_5.addAction(self.action_ch_sentence_low)
        self.menu_5.addAction(self.action_ch_sentence_mid)
        self.menu_5.addAction(self.action_ch_sentence_high)
        self.menu_6.addAction(self.action_en_word_low)
        self.menu_6.addAction(self.action_en_word_mid)
        self.menu_6.addAction(self.action_en_word_high)
        self.menu_7.addAction(self.action_en_sentence_low)
        self.menu_7.addAction(self.action_en_sentence_mid)
        self.menu_7.addAction(self.action_en_sentence_high)
        self.menu.addAction(self.menu_4.menuAction())
        self.menu.addAction(self.menu_5.menuAction())
        self.menu.addAction(self.menu_6.menuAction())
        self.menu.addAction(self.menu_7.menuAction())
        self.menu_2.addAction(self.action_about)
        self.menu_3.addAction(self.action_offline_rank)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "Slim Typer  v1.0"))
        self.radio_ch_word.setText(_translate("mainwindow", "中文词语练习"))
        self.radio_ch_sentence.setText(_translate("mainwindow", "中文句子练习"))
        self.radio_en_word.setText(_translate("mainwindow", "英文单词练习"))
        self.radio_en_sentence.setText(_translate("mainwindow", "英文句子练习"))
        self.radio_key.setText(_translate("mainwindow", "键盘熟悉"))
        self.radio_type.setText(_translate("mainwindow", "打字练习"))
        self.label_welcome.setText(_translate("mainwindow", "欢迎使用   Slim Typer"))
        self.btn_back.setText(_translate("mainwindow", "BACK"))
        self.menu.setTitle(_translate("mainwindow", "难度"))
        self.menu_4.setTitle(_translate("mainwindow", "中文词语(难度)"))
        self.menu_5.setTitle(_translate("mainwindow", "中文句子(难度)"))
        self.menu_6.setTitle(_translate("mainwindow", "英文单词(难度)"))
        self.menu_7.setTitle(_translate("mainwindow", "英文句子(难度)"))
        self.menu_2.setTitle(_translate("mainwindow", "关于"))
        self.menu_3.setTitle(_translate("mainwindow", "纪录"))
        self.action_offline_rank.setText(_translate("mainwindow", "本地排行"))
        self.action_ch_word_low.setText(_translate("mainwindow", "初级"))
        self.action_ch_word_mid.setText(_translate("mainwindow", "中级"))
        self.action_ch_word_high.setText(_translate("mainwindow", "高级"))
        self.action_ch_sentence_low.setText(_translate("mainwindow", "初级"))
        self.action_ch_sentence_mid.setText(_translate("mainwindow", "中级"))
        self.action_ch_sentence_high.setText(_translate("mainwindow", "高级"))
        self.action_en_word_low.setText(_translate("mainwindow", "初级"))
        self.action_en_word_mid.setText(_translate("mainwindow", "中级"))
        self.action_en_word_high.setText(_translate("mainwindow", "高级"))
        self.action_en_sentence_low.setText(_translate("mainwindow", "初级"))
        self.action_en_sentence_mid.setText(_translate("mainwindow", "中级"))
        self.action_en_sentence_high.setText(_translate("mainwindow", "高级"))
        self.action_about.setText(_translate("mainwindow", "About"))

