# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:/python/typer/ui_rankwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rankwindow(object):
    def setupUi(self, rankwindow):
        rankwindow.setObjectName("rankwindow")
        rankwindow.resize(930, 554)
        rankwindow.setMinimumSize(QtCore.QSize(930, 554))
        rankwindow.setMaximumSize(QtCore.QSize(930, 554))
        font = QtGui.QFont()
        font.setFamily("黑体")
        rankwindow.setFont(font)
        rankwindow.setStyleSheet("color=rgb(255, 0, 0)")
        self.cbbox_model = QtWidgets.QComboBox(rankwindow)
        self.cbbox_model.setGeometry(QtCore.QRect(200, 35, 131, 31))
        self.cbbox_model.setObjectName("cbbox_model")
        self.cbbox_model.addItem("")
        self.cbbox_model.addItem("")
        self.cbbox_model.addItem("")
        self.cbbox_model.addItem("")
        self.label = QtWidgets.QLabel(rankwindow)
        self.label.setGeometry(QtCore.QRect(110, 40, 91, 21))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(rankwindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(510, 30, 309, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_low = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_low.setChecked(False)
        self.radio_low.setObjectName("radio_low")
        self.horizontalLayout.addWidget(self.radio_low)
        self.radio_mid = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_mid.setObjectName("radio_mid")
        self.horizontalLayout.addWidget(self.radio_mid)
        self.radio_high = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_high.setObjectName("radio_high")
        self.horizontalLayout.addWidget(self.radio_high)
        self.radio_blank = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_blank.setText("")
        self.radio_blank.setChecked(True)
        self.radio_blank.setObjectName("radio_blank")
        self.horizontalLayout.addWidget(self.radio_blank)
        self.label_2 = QtWidgets.QLabel(rankwindow)
        self.label_2.setGeometry(QtCore.QRect(410, 40, 91, 21))
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(rankwindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 130, 631, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rank_set1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_set1.setObjectName("rank_set1")
        self.horizontalLayout_3.addWidget(self.rank_set1)
        self.rank_time_set1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_time_set1.setObjectName("rank_time_set1")
        self.horizontalLayout_3.addWidget(self.rank_time_set1)
        self.rank_speed_set1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_speed_set1.setObjectName("rank_speed_set1")
        self.horizontalLayout_3.addWidget(self.rank_speed_set1)
        self.rank_marktime_set1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_marktime_set1.setObjectName("rank_marktime_set1")
        self.horizontalLayout_3.addWidget(self.rank_marktime_set1)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 5)
        self.horizontalLayout_3.setStretch(2, 5)
        self.horizontalLayout_3.setStretch(3, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rank_set2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_set2.setObjectName("rank_set2")
        self.horizontalLayout_6.addWidget(self.rank_set2)
        self.rank_time_set2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_time_set2.setObjectName("rank_time_set2")
        self.horizontalLayout_6.addWidget(self.rank_time_set2)
        self.rank_speed_set2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_speed_set2.setObjectName("rank_speed_set2")
        self.horizontalLayout_6.addWidget(self.rank_speed_set2)
        self.rank_marktime_set2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_marktime_set2.setObjectName("rank_marktime_set2")
        self.horizontalLayout_6.addWidget(self.rank_marktime_set2)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 5)
        self.horizontalLayout_6.setStretch(2, 5)
        self.horizontalLayout_6.setStretch(3, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rank_set3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_set3.setObjectName("rank_set3")
        self.horizontalLayout_7.addWidget(self.rank_set3)
        self.rank_time_set3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_time_set3.setObjectName("rank_time_set3")
        self.horizontalLayout_7.addWidget(self.rank_time_set3)
        self.rank_speed_set3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_speed_set3.setObjectName("rank_speed_set3")
        self.horizontalLayout_7.addWidget(self.rank_speed_set3)
        self.rank_marktime_set3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_marktime_set3.setObjectName("rank_marktime_set3")
        self.horizontalLayout_7.addWidget(self.rank_marktime_set3)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 5)
        self.horizontalLayout_7.setStretch(2, 5)
        self.horizontalLayout_7.setStretch(3, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rank_set4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_set4.setObjectName("rank_set4")
        self.horizontalLayout_5.addWidget(self.rank_set4)
        self.rank_time_set4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_time_set4.setObjectName("rank_time_set4")
        self.horizontalLayout_5.addWidget(self.rank_time_set4)
        self.rank_speed_set4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_speed_set4.setObjectName("rank_speed_set4")
        self.horizontalLayout_5.addWidget(self.rank_speed_set4)
        self.rank_marktime_set4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_marktime_set4.setObjectName("rank_marktime_set4")
        self.horizontalLayout_5.addWidget(self.rank_marktime_set4)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 5)
        self.horizontalLayout_5.setStretch(2, 5)
        self.horizontalLayout_5.setStretch(3, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rank_set5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_set5.setObjectName("rank_set5")
        self.horizontalLayout_4.addWidget(self.rank_set5)
        self.rank_time_set5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_time_set5.setObjectName("rank_time_set5")
        self.horizontalLayout_4.addWidget(self.rank_time_set5)
        self.rank_speed_set5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_speed_set5.setObjectName("rank_speed_set5")
        self.horizontalLayout_4.addWidget(self.rank_speed_set5)
        self.rank_marktime_set5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rank_marktime_set5.setObjectName("rank_marktime_set5")
        self.horizontalLayout_4.addWidget(self.rank_marktime_set5)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 5)
        self.horizontalLayout_4.setStretch(2, 5)
        self.horizontalLayout_4.setStretch(3, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(rankwindow)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(190, 80, 631, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(60, -1, 60, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, -1, 90, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 10)

        self.retranslateUi(rankwindow)
        QtCore.QMetaObject.connectSlotsByName(rankwindow)

    def retranslateUi(self, rankwindow):
        _translate = QtCore.QCoreApplication.translate
        rankwindow.setWindowTitle(_translate("rankwindow", "查看记录"))
        self.cbbox_model.setItemText(0, _translate("rankwindow", "中文词语模式"))
        self.cbbox_model.setItemText(1, _translate("rankwindow", "中文句子模式"))
        self.cbbox_model.setItemText(2, _translate("rankwindow", "英文单词模式"))
        self.cbbox_model.setItemText(3, _translate("rankwindow", "英文句子模式"))
        self.label.setText(_translate("rankwindow", "模式选择:"))
        self.radio_low.setText(_translate("rankwindow", "初级"))
        self.radio_mid.setText(_translate("rankwindow", "中级"))
        self.radio_high.setText(_translate("rankwindow", "高级"))
        self.label_2.setText(_translate("rankwindow", "难度选择:"))
        self.rank_set1.setText(_translate("rankwindow", "1"))
        self.rank_time_set1.setText(_translate("rankwindow", "0时0分0秒"))
        self.rank_speed_set1.setText(_translate("rankwindow", "0.00字/秒"))
        self.rank_marktime_set1.setText(_translate("rankwindow", "2018-2-12 22：49"))
        self.rank_set2.setText(_translate("rankwindow", "2"))
        self.rank_time_set2.setText(_translate("rankwindow", "0时0分0秒"))
        self.rank_speed_set2.setText(_translate("rankwindow", "0.00字/秒"))
        self.rank_marktime_set2.setText(_translate("rankwindow", "2018-2-12 22：49"))
        self.rank_set3.setText(_translate("rankwindow", "3"))
        self.rank_time_set3.setText(_translate("rankwindow", "0时0分0秒"))
        self.rank_speed_set3.setText(_translate("rankwindow", "0.00字/秒"))
        self.rank_marktime_set3.setText(_translate("rankwindow", "2018-2-12 22：49"))
        self.rank_set4.setText(_translate("rankwindow", "4"))
        self.rank_time_set4.setText(_translate("rankwindow", "0时0分0秒"))
        self.rank_speed_set4.setText(_translate("rankwindow", "0.00字/秒"))
        self.rank_marktime_set4.setText(_translate("rankwindow", "2018-2-12 22：49"))
        self.rank_set5.setText(_translate("rankwindow", "5"))
        self.rank_time_set5.setText(_translate("rankwindow", "0时0分0秒"))
        self.rank_speed_set5.setText(_translate("rankwindow", "0.00字/秒"))
        self.rank_marktime_set5.setText(_translate("rankwindow", "2018-2-12 22：49"))
        self.label_4.setText(_translate("rankwindow", "用时"))
        self.label_5.setText(_translate("rankwindow", "完成速度"))
        self.label_3.setText(_translate("rankwindow", "记录时间"))

